name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality:
    strategy:
      fail-fast: true
      matrix:
        node-version: [20.x, 22.x]
    uses: ./.github/workflows/quality.yml
    with:
      node-version: ${{ matrix.node-version }}
